language: node_js
node_js:
  - "4.2.6"
script: "npm run $TEST_STEP"
env:
  matrix:
    - TEST_STEP=jscpd
    - TEST_STEP=lint
    - TEST_STEP=test
    - TEST_STEP=flow
notifications:
  email: false
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
