language: node_js
node_js:
  - "0.10"
script: "npm run $TEST_STEP"
env:
  matrix:
    - TEST_STEP=lint
    - TEST_STEP=test
notifications:
  email: false
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
